name: Build rootless DEB

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: waruhachi/theos-action@v2.4.6
        with:
          theos-src: 'theos/theos'
          theos-branch: 'master'
          sdks-src: 'theos/sdks'
          sdks-branch: 'master'
          libgcuniversal: true
          libgcuniversal-src: 'MrGcGamer/LibGcUniversalDocumentation'
          libgcuniversal-branch: 'master'
          altlist: true
          altlist-src: 'opa334/AltList'
          altlist-branch: 'main'
      
      - name: Build rootless package
        run: make clean package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless

      - name: Upload DEB artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flexing-rootless-debs
          path: |
            packages/*.deb
          if-no-files-found: error
